### ISSUE TITLE
Build errors on 

### ISSUE THREAD

**Issue by pgatt** [Moaneschien/4rack#1]
Hi there,

Linked below is the list of errors I am getting when trying to build.

https://www.dropbox.com/s/oaspa5x42bhqhbq/Moaneschien%20Errors.txt?dl=0

**Comment by pgatt** [comment]
Still doing - error: reference to 'string' is ambiguous
they seem to be the only four errors left.

**Comment by Moaneschien** [comment]
Added #include <string>, that should do it I hope.

**Comment by pgatt** [comment]
String ambiguous errors here still.

**Comment by Moaneschien** [comment]
Ok. Removed the string completely as they didn't add anything.

**Comment by pgatt** [comment]
It's now failing on Ramp the same way.

**Comment by Moaneschien** [comment]
updated ramp, if you would try again. Thanks!

**Comment by pgatt** [comment]
Got it and it worked! Thanks for the speedy fix!

**Comment by Moaneschien** [comment]
Excellent. Thank you again.
