### ISSUE TITLE
Bezosc.svg -> bezosc.svg in src/Bezosc.cpp

### ISSUE THREAD

**Issue by hexdump0815** [Moaneschien/4rack#2]
i think Bezosc.svg should be changed to bezosc.svg in src/Bezosc.cpp so that it will work properly on systems with case sensitive filenames (linux) - otherwise it will not find its svg as included in the res dir is only bezosc.svg

best wishes - hexdump

**Comment by Moaneschien** [comment]
Done. Thanks.
